const colorOptions = [
  { value: "red", name: "Vermelho", hex: "#dc2626" },
  { value: "green", name: "Verde", hex: "#16a34a" },
  { value: "blue", name: "Azul", hex: "#2563eb" },
  { value: "yellow", name: "Amarelo", hex: "#eab308" },
  { value: "orange", name: "Laranja", hex: "#ea580c" },
  { value: "purple", name: "Roxo", hex: "#9333ea" },
  { value: "pink", name: "Rosa", hex: "#db2777" },
  { value: "brown", name: "Marrom", hex: "#92400e" },
  { value: "gray", name: "Cinza", hex: "#6b7280" },
  { value: "black", name: "Preto", hex: "#000000" },
  { value: "white", name: "Branco", hex: "#ffffff" },
  { value: "cyan", name: "Ciano", hex: "#06b6d4" },
  { value: "magenta", name: "Magenta", hex: "#c026d3" },
  { value: "lime", name: "Lima", hex: "#84cc16" },
  { value: "teal", name: "Verde Azulado", hex: "#0d9488" },
  { value: "indigo", name: "Índigo", hex: "#4f46e5" },
  { value: "emerald", name: "Esmeralda", hex: "#10b981" },
  { value: "amber", name: "Âmbar", hex: "#f59e0b" },
];
